[config]
schemaVersion = "0.0.1"


[package]
namespace = "adamant"
name = "Modpack_Core"
versionNumber = "1.0.0"
description = "Coordinator for the adamant H2 modpack - unified UI, profiles, and config hashing."
websiteUrl = "https://github.com/maybe-adamant/h2-modpack-Core"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ModUtil = "4.0.1"
adamant-Modpack_Lib = "1.0.0"
adamant-BraidFix = "1.0.0"
adamant-CardioTorchFix = "1.0.0"
adamant-CharybdisBehavior = "1.0.0"
adamant-CorrosionFix = "1.0.0"
adamant-DisableArachnePity = "1.0.0"
adamant-DisableSeleneBeforeBoon = "1.0.0"
adamant-EscalatingFigLeaf = "1.0.0"
adamant-ETFix = "1.0.0"
adamant-ExtraDoseFix = "1.0.0"
adamant-FamiliarDelayFix = "1.0.0"
adamant-FirstHammer = "1.0.0"
adamant-ForceArachne = "1.0.0"
adamant-ForceMedea = "1.0.0"
adamant-GGGFix = "1.0.0"
adamant-KBMEscape = "1.0.0"
adamant-MiniBossEncounterFix = "1.0.0"
adamant-OmegaCastFix = "1.0.0"
adamant-PoseidonWavesFix = "1.0.0"
adamant-PreventEchoScam = "1.0.0"
adamant-RTAMode = "1.0.0"
adamant-SecondStageChanneling = "1.0.0"
adamant-SeleneFix = "1.0.0"
adamant-ShimmeringFix = "1.0.0"
adamant-ShowLocation = "1.0.0"
adamant-SkipDeathCutscene = "1.0.0"
adamant-SkipDialogue = "1.0.0"
adamant-SkipGemBossReward = "1.0.0"
adamant-SkipRunEndCutscene = "1.0.0"
adamant-SpawnLocation = "1.0.0"
adamant-SpeedrunTimer = "1.0.0"
adamant-StagedOmegaFix = "1.0.0"
adamant-SufferingFix = "1.0.0"
adamant-SurfaceStructure = "1.0.0"
adamant-TidalRingFix = "1.0.0"
adamant-VictoryScreen = "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Uncomment (remove the #) the three lines below if you have any files to copy to the plugins_data folder (like custom .pkg files)
# [[build.copy]]
# source = "./data"
# target = "./plugins_data"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
